<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class HistorySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('reg_history')->insert([
            [
                'id_user' => 1,
                'id_exam' => 1,
                'attempt_number' => 1,
                'status' => 'completed',
                'started_at' => Carbon::now()->subDays(5),
                'completed_at' => Carbon::now()->subDays(5)->addMinutes(50),
                'time_used' => 50,
                'score' => 85,
                'correct_answers' => 21,
                'passed' => true,
                'answers' => json_encode([1 => 'A', 2 => 'C', 3 => 'B']), // ejemplo
                'question_order' => json_encode([1,2,3]),
                'ip_address' => '192.168.0.1',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
                'metadata' => json_encode(['browser' => 'chrome']),
            ],
            [
                'id_user' => 1,
                'id_exam' => 1,
                'attempt_number' => 2,
                'status' => 'completed',
                'started_at' => Carbon::now()->subDays(3),
                'completed_at' => Carbon::now()->subDays(3)->addMinutes(55),
                'time_used' => 55,
                'score' => 78,
                'correct_answers' => 19,
                'passed' => true,
                'answers' => json_encode([1 => 'B', 2 => 'C', 3 => 'D']),
                'question_order' => json_encode([1,2,3]),
                'ip_address' => '192.168.0.2',
                'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
                'metadata' => json_encode(['browser' => 'safari']),
            ],
            [
                'id_user' => 1,
                'id_exam' => 1,
                'attempt_number' => 3,
                'status' => 'in_progress',
                'started_at' => Carbon::now()->subDay(),
                'completed_at' => null,
                'time_used' => 30,
                'score' => 50,
                'correct_answers' => 10,
                'passed' => false,
                'answers' => json_encode([]),
                'question_order' => json_encode([1,2,3]),
                'ip_address' => '192.168.0.1',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
                'metadata' => json_encode(['browser' => 'chrome']),
            ],
            [
                'id_user' => 1,
                'id_exam' => 1,
                'attempt_number' => 4,
                'status' => 'in_progress',
                'started_at' => Carbon::now()->subDay(),
                'completed_at' => null,
                'time_used' => 30,
                'score' => 50,
                'correct_answers' => 10,
                'passed' => false,
                'answers' => json_encode([]),
                'question_order' => json_encode([1,2,3]),
                'ip_address' => '192.168.0.1',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
                'metadata' => json_encode(['browser' => 'chrome']),
            ],
            [
                'id_user' => 1,
                'id_exam' => 1,
                'attempt_number' => 5,
                'status' => 'in_progress',
                'started_at' => Carbon::now()->subDay(),
                'completed_at' => null,
                'time_used' => 30,
                'score' => 50,
                'correct_answers' => 10,
                'passed' => false,
                'answers' => json_encode([]),
                'question_order' => json_encode([1,2,3]),
                'ip_address' => '192.168.0.1',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
                'metadata' => json_encode(['browser' => 'chrome']),
            ],
            [
                'id_user' => 1,
                'id_exam' => 1,
                'attempt_number' => 6,
                'status' => 'in_progress',
                'started_at' => Carbon::now()->subDay(),
                'completed_at' => null,
                'time_used' => 30,
                'score' => 50,
                'correct_answers' => 10,
                'passed' => false,
                'answers' => json_encode([]),
                'question_order' => json_encode([1,2,3]),
                'ip_address' => '192.168.0.1',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
                'metadata' => json_encode(['browser' => 'chrome']),
            ],
            [
                'id_user' => 1,
                'id_exam' => 1,
                'attempt_number' => 7,
                'status' => 'in_progress',
                'started_at' => Carbon::now()->subDay(),
                'completed_at' => null,
                'time_used' => 30,
                'score' => 50,
                'correct_answers' => 10,
                'passed' => false,
                'answers' => json_encode([]),
                'question_order' => json_encode([1,2,3]),
                'ip_address' => '192.168.0.1',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
                'metadata' => json_encode(['browser' => 'chrome']),
            ],
            [
                'id_user' => 1,
                'id_exam' => 1,
                'attempt_number' => 8,
                'status' => 'in_progress',
                'started_at' => Carbon::now()->subDay(),
                'completed_at' => null,
                'time_used' => 30,
                'score' => 50,
                'correct_answers' => 10,
                'passed' => false,
                'answers' => json_encode([]),
                'question_order' => json_encode([1,2,3]),
                'ip_address' => '192.168.0.1',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
                'metadata' => json_encode(['browser' => 'chrome']),
            ],
            [
                'id_user' => 1,
                'id_exam' => 1,
                'attempt_number' => 9,
                'status' => 'in_progress',
                'started_at' => Carbon::now()->subDay(),
                'completed_at' => null,
                'time_used' => 30,
                'score' => 50,
                'correct_answers' => 10,
                'passed' => false,
                'answers' => json_encode([]),
                'question_order' => json_encode([1,2,3]),
                'ip_address' => '192.168.0.1',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
                'metadata' => json_encode(['browser' => 'chrome']),
            ],
            [
                'id_user' => 1,
                'id_exam' => 1,
                'attempt_number' => 10,
                'status' => 'in_progress',
                'started_at' => Carbon::now()->subDay(),
                'completed_at' => null,
                'time_used' => 30,
                'score' => 50,
                'correct_answers' => 10,
                'passed' => false,
                'answers' => json_encode([]),
                'question_order' => json_encode([1,2,3]),
                'ip_address' => '192.168.0.1',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
                'metadata' => json_encode(['browser' => 'chrome']),
            ],
        ]);
    }
}
